//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoorElain_0522069_Day1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Table2
    {
        public int user_id { get; set; }
        public string Username { get; set; }
        public string User_Password { get; set; }
        public Nullable<int> Age { get; set; }
        public byte[] Gender_bin { get; set; }
        public string Gender_var { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
    }
}
